"""Only normalized broker operations may enter the execution engine."""

from datetime import datetime
from typing import Protocol

from .models import AccountSnapshot, OrderIntent, OrderResult, Preview, Quote


class BrokerAdapter(Protocol):
    mode: str

    def snapshot(self, now: datetime) -> AccountSnapshot: ...
    def quote(self, instrument: str, now: datetime) -> Quote: ...
    def preview(self, intent: OrderIntent, now: datetime) -> Preview: ...
    def submit(self, intent: OrderIntent, now: datetime) -> OrderResult: ...
    def lookup(self, request_id: str, now: datetime) -> OrderResult: ...
    def cancel(self, request_id: str, now: datetime) -> OrderResult: ...
